# Generated by Django 5.2.5 on 2025-08-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_apps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, help_text='The city or area this restaurant serves.', max_length=100, verbose_name='Location'),
        ),
    ]
