# Generated by Django 5.2.5 on 2025-08-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailcustomer',
            name='address',
        ),
        migrations.AddField(
            model_name='retailcustomer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='retailcustomer',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='retailcustomer',
            name='default_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card')], default='credit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='retailcustomer',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='retailcustomer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip Code'),
        ),
    ]
