# Generated by Django 5.2.5 on 2025-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_customer', '0003_remove_retailcustomer_address_retailcustomer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcustomer',
            name='created_att',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
