# Generated by Django 5.2.5 on 2025-08-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_payroll', models.BooleanField(default=True)),
                ('default_payment_method', models.CharField(choices=[('payroll', 'Payroll'), ('cash', 'Cash'), ('credit_card', 'Credit Card')], default='payroll', max_length=20)),
            ],
        ),
    ]
