# Generated by Django 5.2.5 on 2025-08-14 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('shared_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_core.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.businessclient'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
