# Generated by Django 5.2.5 on 2025-08-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessclient',
            name='company',
        ),
    ]
