# Generated by Django 5.2.5 on 2025-08-15 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_businessclient_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessclient',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='businessclient',
            name='default_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card')], default='credit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
