# Generated by Django 5.2.5 on 2025-08-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_contact_email_businessclient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='is_businessaddmin',
            field=models.BooleanField(default=False),
        ),
    ]
