# Generated by Django 5.2.5 on 2025-08-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessclient_is_businessaddmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessclient',
            name='is_businessaddmin',
        ),
    ]
