# Generated by Django 5.2.5 on 2025-08-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_businessclient_is_businessaddmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='is_businessaddmin',
            field=models.BooleanField(default=False),
        ),
    ]
