# Generated by Django 5.2.5 on 2025-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_businessclient_is_businessaddmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessclient',
            name='address',
        ),
        migrations.AddField(
            model_name='businessclient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
