# Generated by Django 5.2.5 on 2025-08-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_businessclient_address_businessclient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip Code'),
        ),
    ]
