# Generated by Django 5.2.5 on 2025-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_employee_city_employee_country_employee_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='created_att',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
