# Generated by Django 5.2.5 on 2025-08-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businessclient_created_att'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_summaries', to='business.businessclient')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_summaries', to='business.employee')),
            ],
            options={
                'unique_together': {('employee', 'business_client')},
            },
        ),
    ]
