# Generated by Django 5.2.5 on 2025-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_businessaddmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tenantadmin',
            field=models.BooleanField(default=False),
        ),
    ]
