# Generated by Django 5.2.5 on 2025-08-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_core', '0002_user_is_businessaddmin_user_is_tenantadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_businessaddmin',
            new_name='is_businessadmin',
        ),
    ]
