# Generated by Django 5.2.5 on 2025-08-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_core', '0003_rename_is_businessaddmin_user_is_businessadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('restaurant_admin', 'Restaurant Admin'), ('business_admin', 'Business Admin'), ('employee', 'Employee'), ('retail_customer', 'Retail Customer')], max_length=50),
        ),
    ]
