# Generated by Django 5.2.5 on 2025-08-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_core', '0004_alter_company_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_att',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
