# Generated by Django 5.2.5 on 2025-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_by_business',
            field=models.BooleanField(default=False),
        ),
    ]
