# Generated by Django 5.2.5 on 2025-08-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('retail_customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retail_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail_customer.retailcustomer'),
        ),
    ]
