# Generated by Django 5.2.5 on 2025-08-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_by_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_by_business',
            new_name='is_paid_by_business',
        ),
    ]
