# Generated by Django 5.2.5 on 2025-08-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('shared_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shared_core.company'),
        ),
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(related_name='combos', to='catalog.product'),
        ),
    ]
