# Generated by Django 5.2.5 on 2025-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
