# Generated by Django 5.2.5 on 2025-08-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_combo_description'),
        ('shared_core', '0003_rename_is_businessaddmin_user_is_businessadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='shared_core.company'),
        ),
    ]
